// THEMES — organized by unhinged level, 1 (wholesome) through 5 (unhinged).
// Deliberately a mixed bag within each level: food, movies, music, hypotheticals,
// confessions, philosophical tangents, dark humor, whatever. Add more any time —
// arrays can be any length.

const THEMES = {
  1: {
    name: "Wholesome",
    list: [
      "Comfort foods that instantly fix a bad day",
      "Movies you could rewatch forever and never get sick of",
      "Songs that make you cry the good kind of tears",
      "A childhood show you were way too obsessed with",
      "The dream vacation you'd drop everything for",
      "The best gift you've ever given or received",
      "A meal you'd pick as your actual last meal",
      "A book that quietly changed how you see the world",
      "Smells that instantly bring back a specific memory",
      "The most \"us\" inside joke you two have",
      "A skill you wish you'd learned as a kid",
      "Your ideal lazy Sunday, minute by minute",
      "An album that got you through a specific era of your life",
      "The best meal either of you has ever cooked",
      "A stranger's small act of kindness you still think about",
      "The most underrated season and why",
      "A teacher or mentor who quietly changed your trajectory",
      "The best trip you've ever taken, plan or no plan",
      "A tradition you want to start and keep forever",
      "The most satisfying \"click\" of your life — when something finally made sense",
      "Your go-to karaoke song and why it's non-negotiable",
      "A place that feels like home even though you don't live there",
      "The best piece of advice you've ever actually followed",
      "A hobby you'd pick up in a heartbeat with infinite time and money",
      "The animal you'd want as a familiar, and why",
      "A meal that instantly means \"celebration\" to you",
      "The most beautiful thing you've seen in person",
      "A friendship that started in the most random way",
      "The best surprise anyone has ever pulled off for you",
      "A childhood game you could still play for hours",
      "The coziest place you've ever spent a rainy afternoon",
      "A recipe passed down in your family that you'd protect with your life",
      "The best live show or concert you've ever been to",
      "A compliment someone gave you that you still think about",
      "The most peaceful moment you've had in the last year",
      "A fictional character you'd want as a best friend",
      "The best local spot only people from your area know about",
      "A song that instantly puts you in a good mood no matter what",
      "The proudest you've ever been of a friend",
      "A childhood snack you'd still fight someone over",
      "The best decision you've ever made on a total whim",
      "A tiny daily ritual that makes your life better",
      "The most underrated holiday and why it deserves more love",
      "A museum, gallery, or exhibit that actually changed how you think",
      "Your dream dinner party guest list, living or dead",
      "The best piece of unsolicited advice a stranger ever gave you",
      "A show you'd want to live inside of for a week",
      "The first concert or live event you ever went to",
      "A language you wish you'd grown up speaking",
      "The most magical thing about where you grew up",
      "A gift you're still planning that no one knows about",
      "The best \"we should do this every year\" tradition you have",
      "A moment nature completely stopped you in your tracks",
      "The coziest fictional home you wish were real",
      "A compliment you gave that clearly meant more than you realized",
      "The best thing about the town or city you grew up in",
      "A skill your parents or grandparents had that you wish you'd learned",
      "Your favorite way to spend a completely free day, no plans allowed",
      "The best thing you've ever built or made with your hands",
      "A song lyric that feels like it was written about your life",
      "The most wholesome thing you've seen strangers do for each other",
      "A childhood bedroom detail you still think about",
      "The best campfire or backyard story you have, no scary parts allowed",
      "A place you've never been but feel oddly connected to",
      "The proudest moment of your life so far",
      "A recipe you want to master before you die",
      "The best thing about getting older that no one warns you about",
      "A tiny habit that's quietly made your life better",
      "The most comforting sound in the world to you",
      "A book, movie, or show you recommend to literally everyone",
      "The best gift you've ever given without being asked",
      "A place you go, physically or mentally, when you need to reset",
      "The most \"main character energy\" wholesome moment you've had",
      "A person who believed in you before you believed in yourself",
      "The best thing about your current daily routine",
      "A dream you actually achieved and almost forgot to celebrate",
      "The coziest season activity that never gets old",
      "A pet you've loved that changed how you see animals",
      "The best thing someone has ever done for you with zero explanation",
      "A recipe, meal, or dish that instantly makes you feel like a kid again",
      "The most underrated love language, in your opinion",
      "A moment you felt completely at peace with exactly where you were",
      "The best thing about your closest friendship",
      "A place you'd want your ashes scattered, purely for the view",
      "The most satisfying purchase you've ever made under $20",
      "A childhood fear that turned out to be adorable in hindsight",
      "The best thing about the family you were born into or chose",
      "A song you'd want played at your wedding, hypothetical or real",
      "The most beautiful sunrise or sunset you've ever seen",
      "A tiny act of kindness you've never told anyone about",
      "The best thing about where you live right now",
      "A dream job you'd take even for free, purely for the joy of it",
      "The most comforting piece of clothing you own",
      "A moment a stranger's kindness completely changed your day",
      "The best thing you've ever taught someone else",
      "A place that instantly makes you feel like a kid on summer break",
      "The most wholesome rivalry you've ever had with a sibling or friend",
      "A gift idea you're saving for the perfect moment",
      "The best thing about slow mornings",
      "A tradition from your childhood you hope to pass on",
      "The most beautiful piece of music you've ever heard live",
      "A stranger you'll never see again who made your whole day",
      "The best \"no phones\" memory you have",
      "A recipe box or cookbook that feels like a family heirloom",
      "The most peaceful place you've ever fallen asleep",
      "A childhood collection you were way too proud of",
      "The best thing about your favorite holiday that has nothing to do with gifts",
      "A moment you felt truly, completely understood by someone",
      "The best home-cooked meal you've had that wasn't yours or family's",
      "The most wholesome thing on your bucket list",
    ],
  },
  2: {
    name: "Spicy",
    list: [
      "Worst first dates either of you has ever been on",
      "Unpopular food opinions you will die defending",
      "The most embarrassing thing in your search history",
      "A celebrity you'd trade lives with for exactly one week",
      "The worst fashion phase you thought was fire at the time",
      "Conspiracy theories you low-key believe",
      "The weirdest thing you've done to try to fall asleep",
      "A lie you told as a kid that spiraled way out of control",
      "The worst gift you ever had to pretend to love",
      "The most feral thing you've eaten at 2am",
      "A text you sent and immediately regretted",
      "Weird family traditions that seem normal until you say them out loud",
      "A movie everyone loves that you secretly think is bad",
      "The most chaotic thing that's happened at a family holiday",
      "A song you're embarrassed to admit you know every word to",
      "The pettiest thing you've ever held a grudge over",
      "A rumor about you that was somehow both false and extremely on-brand",
      "The worst advice you've ever given with total confidence",
      "A group project villain origin story",
      "The most \"main character\" thing you've ever done in public",
      "Something you're irrationally competitive about",
      "A time you were 100% sure you were right and were extremely wrong",
      "The weirdest compliment you've ever received",
      "A childhood fear that's honestly still a little valid",
      "The worst customer service experience you've caused, not received",
      "An ick that's ended things before they even started",
      "A conversation you've rehearsed in the shower and never had",
      "The most unnecessary thing you've ever bought at full price",
      "A celebrity feud you have unreasonably strong opinions about",
      "The worst haircut decision you've ever made and stood by anyway",
      "A white lie you're still maintaining to this day",
      "The most petty text argument you've ever had",
      "A trend you were embarrassingly late to and pretended you weren't",
      "The worst thing you've said out loud thinking your mic was off",
      "A \"so and so is the worst\" opinion you will not be talked out of",
      "The most unhinged thing you've done to win a board game",
      "A celebrity you have a completely irrational soft spot for",
      "The worst outfit you've ever been photographed in",
      "A grudge you're holding against a fictional character",
      "The most embarrassing thing that's ever autoplayed in front of someone",
      "A time you clapped back and immediately regretted your delivery",
      "The worst thing you've ever said to get out of an argument",
      "A childhood crush that makes zero sense in hindsight",
      "The most petty thing you've ever done to a roommate",
      "A show you watch purely to talk about how bad it is",
      "The worst thing you've ever eaten to be polite",
      "A \"prove me wrong\" opinion you will absolutely die on",
      "The most chaotic thing that's happened during an online order",
      "A time you pretended to have read or watched something you hadn't",
      "The worst thing you've done to avoid small talk",
      "A celebrity you'd fight for absolutely no reason",
      "The most unhinged thing you've screenshotted and sent without context",
      "A time you lost an argument you knew you were winning",
      "The worst gift-wrapping disaster you've ever caused",
      "A song you skip in front of people but blast alone",
      "The most chaotic thing that's ever happened at karaoke",
      "A time you accidentally started a rumor",
      "The worst thing you've said mid-argument that you didn't mean",
      "A \"this is a hill I will die on\" food opinion",
      "The most petty thing you've done to win a family game night",
      "A time your autocorrect completely betrayed you in public",
      "The worst thing you've done for a good parking spot",
      "A celebrity crush from childhood you're mildly embarrassed by now",
      "The most chaotic group chat argument you've been part of",
      "A time you 100% overreacted and have never admitted it",
      "The worst thing you've done to avoid answering a text",
      "A trend everyone loved that you never understood",
      "The most unhinged thing you've done for a discount",
      "A time you were caught talking about someone by that exact someone",
      "The worst impulse decision you've made in a store",
      "A celebrity you'd let roast you and thank them for it",
      "The most petty revenge you've taken on a sibling",
      "A time you faked being sick and it went too well",
      "The worst thing you've said to get someone to leave you alone",
      "A childhood tattletale story you're not proud of",
      "The most unhinged thing you've done for a good photo",
      "A time you were \"that person\" at a party and knew it",
      "The worst thing you've done to win an online argument",
      "A celebrity feud you'd insert yourself into given the chance",
      "The most petty thing you've ever done at a self-checkout",
      "A time you lied about your location and got caught",
      "The worst thing you've done purely because you were bored",
      "A conspiracy theory about a friend group you low-key believe",
      "The most chaotic thing that's happened during a video call",
      "A time you regretted hitting \"reply all\"",
      "The worst thing you've said in the heat of a game night",
      "A celebrity you think is overrated and will die defending",
      "The most unhinged thing you've done to avoid a coworker",
      "A time you were dramatically wrong about how popular an opinion was",
      "The worst decision you've made based purely on vibes",
      "A childhood nickname you're still a little haunted by",
      "The most petty thing you've done in a group project",
      "A time you were 100% the problem and knew it in real time",
      "The worst thing you've done to end a phone call faster",
      "A celebrity you'd want to co-host a podcast with purely for chaos",
      "The most unhinged thing you've said to a customer service rep",
      "A time you were caught mid-lie and had to improvise",
      "The worst thing you've done for free food",
      "A trend you're still embarrassed you fell for",
      "The most chaotic thing that's happened on a group trip so far",
      "A time your poker face completely failed you",
      "The worst excuse you've ever used and gotten away with",
      "A celebrity you think would be a nightmare to date",
      "The most petty thing you've done over a parking spot",
      "A time you were wildly overconfident and paid for it",
      "The worst thing you've said during a game that got too competitive",
      "A rumor you started that got wildly out of hand",
      "The most unhinged thing you've done to avoid small talk at a party",
      "A celebrity opinion you know is unpopular and refuse to change",
      "The worst thing you've ever done for a good review online",
    ],
  },
  3: {
    name: "Chaotic",
    list: [
      "Worst decision either of you made while drunk",
      "The weirdest DM or text you've ever gotten from a stranger",
      "Something you did for a crush that mortifies you now",
      "The worst roommate horror story you have",
      "A dream so weird you had to tell someone immediately",
      "The most unhinged thing you Googled and instantly regretted",
      "A time you got away with something you definitely shouldn't have",
      "The white lie that snowballed into total chaos",
      "Something you did in public that still haunts you",
      "The most feral your group chat has ever gotten",
      "A \"we don't talk about that night\" story",
      "The weirdest internet rabbit hole you've ever fallen into",
      "The worst movie you've ever paid full price to see",
      "A time you had to fake being fine in front of everyone",
      "The most chaotic thing you've done to avoid an awkward conversation",
      "The strangest thing you've overheard as a total stranger",
      "A friendship breakup that hit harder than any romantic one",
      "The most unhinged thing a stranger has told you at a bar",
      "A time you accidentally became the villain of someone else's story",
      "The weirdest job interview you've ever sat through, either side of the table",
      "Something you did purely out of spite and don't regret at all",
      "A time your gut instinct saved you from something you can't even explain",
      "The most chaotic wedding, party, or event you've witnessed firsthand",
      "A secret talent you have that makes zero sense",
      "The worst way you've ever found out someone was talking about you",
      "A time you had to pretend to know someone you had absolutely no memory of",
      "The strangest coincidence that's ever happened to you",
      "A time you got locked out somewhere at the worst possible moment",
      "The most chaotic thing that's happened to you while traveling alone",
      "A stranger's secret you accidentally ended up knowing",
      "The weirdest thing you've done to get out of a lease or contract",
      "A time a group chat completely turned on someone, deservedly or not",
      "The most unhinged thing you've done during a power outage",
      "A time you were dragged into someone else's drama with zero warning",
      "The strangest thing a coworker has ever confided in you",
      "A time you had to think on your feet to avoid total disaster",
      "The most chaotic thing that's happened during a job you no longer have",
      "A conspiracy your friend group has about someone, half-joking, half-not",
      "The weirdest thing you've witnessed happen to a stranger in public",
      "A time you were absolutely certain you were being followed or watched",
      "The most unhinged thing you've done during a layover",
      "A secret you found out by accident and immediately wished you hadn't",
      "The strangest neighbor story you have",
      "A time you had to lie to a police officer, security guard, or bouncer",
      "The most chaotic thing that's happened on a night that started completely normal",
      "A time you were the only sober one and had to manage total chaos",
      "The weirdest thing that's ever happened to you at 4am",
      "A time you accidentally witnessed a breakup, proposal, or fight in public",
      "The most unhinged thing you've done to make rent",
      "A time a stranger's kindness turned out to be deeply suspicious",
      "The strangest thing you've found in a rental, hotel, or Airbnb",
      "A time you had to pretend an emergency was smaller than it was",
      "The most chaotic thing that's happened to you at the DMV, airport, or any government office",
      "A time your phone died at the absolute worst moment",
      "The weirdest thing you've done to get someone's attention",
      "A time you were completely convinced a place was haunted",
      "The most unhinged thing you've done because you were running late",
      "A secret your friend group has kept from one specific person, for their own good",
      "The strangest thing that's ever happened during a work happy hour",
      "A time you had to talk your way out of something with zero prep",
      "The most chaotic thing that's happened to you on public transportation",
      "A time you were genuinely scared and didn't tell anyone until much later",
      "The weirdest thing a stranger has ever handed you or given you",
      "A time you had to choose between two friends and it got messy",
      "The most unhinged thing you've done to avoid paying for something",
      "A secret meeting spot you've had that no one else knew about",
      "The strangest thing you've ever found scrolling through old photos",
      "A time you were absolutely sure something supernatural just happened",
      "The most chaotic thing you've witnessed at a wedding that wasn't yours",
      "A time a plan completely fell apart and somehow worked out better",
      "The weirdest thing you've done in the name of \"closure\"",
      "A secret you kept for a friend that you still think about",
      "The most unhinged thing that's happened during a road trip",
      "A time you were mistaken for someone else and just went with it",
      "The strangest thing that's ever happened to you in an elevator",
      "A time you overheard your own name in a conversation you weren't part of",
      "The most chaotic thing that's happened during a work trip",
      "A secret hiding spot from childhood that still exists",
      "The weirdest thing you've done to avoid running into someone",
      "A time you had to keep a straight face through something absolutely unhinged",
      "The most unhinged thing that's happened to you at a concert or festival",
      "A time a stranger completely changed the trajectory of your night",
      "The strangest thing you've ever found left behind in a rideshare",
      "A time you got roped into a scheme you had no business being part of",
      "The most chaotic thing that's happened during a group vacation",
      "A secret you almost told the wrong person",
      "The weirdest thing you've overheard through a wall",
      "A time you had to improvise an entire alibi",
      "The most unhinged thing that's happened to you during a storm or natural event",
      "A stranger you helped who turned out to be more than they seemed",
      "The strangest thing that's ever happened to you at a laundromat, gym, or other public space",
      "A time your entire night was derailed by one text",
      "The most chaotic thing that's happened to you because of a wrong number",
      "A secret handshake, code, or signal your friend group actually uses",
      "The weirdest thing you've done to test if someone was lying to you",
      "A time you were 100% sure you'd get caught and somehow didn't",
      "The most unhinged thing that's happened to you because of a dating app",
      "A stranger's argument you accidentally became the deciding vote in",
      "The strangest thing you've ever seen someone do at 3am in public",
      "A time your entire plan hinged on a stranger and it actually worked",
      "The most chaotic thing that's happened during a \"quick errand\"",
      "A secret you've kept that would honestly surprise no one",
      "The weirdest thing you've done to avoid a bill",
      "A time you were genuinely unsure if something was a dream or real",
      "The most unhinged thing that's happened to you in a group project as an adult",
      "A stranger's overheard phone call that lived in your head rent free",
      "The strangest thing that's ever happened to you house-sitting or pet-sitting",
      "A time your entire week got derailed by one bad decision",
      "The most chaotic thing that's happened to you because you said yes to literally anything",
      "A secret talent your friend has that they refuse to show anyone",
    ],
  },
  4: {
    name: "Feral",
    list: [
      "Worst hookup story either of you is willing to share",
      "Something embarrassing you got fully caught doing",
      "The worst breakup revenge either of you has pulled or witnessed",
      "The strangest thing you've done at 3am and questioned everything after",
      "The weirdest thing you've heard someone say during a hookup",
      "The most illegal thing you've done and fully gotten away with",
      "A time your body betrayed you at the worst possible moment",
      "The most unhinged thing an ex has ever done",
      "Weirdest thing that's ever happened on public transit near you",
      "A secret you've kept from your family that would break the internet",
      "The most chaotic thing you've done for petty revenge",
      "A time you had to lie your way out of getting caught",
      "The worst thing someone has confidently recommended you eat",
      "A situationship so strange you still can't explain it",
      "The most unhinged voicemail or text you've ever received",
      "The worst \"we need to talk\" conversation you've had on either end",
      "A time you were absolutely certain you were about to die and weren't",
      "The most feral thing you've done to win an argument",
      "Something you did for attention that you'd never admit sober",
      "The strangest thing that's ever happened to you in someone else's house",
      "A time you had to choose between two terrible options and picked wrong",
      "The most unhinged thing you've done to get out of plans",
      "A secret rivalry you have with someone who has no idea it exists",
      "The worst thing you've ever walked in on",
      "A time you got caught in a lie and just kept going",
      "The most chaotic thing that's happened to you on a first date",
      "A time an ex tried to come back and it went badly for them",
      "The worst thing you've done while pretending to be asleep",
      "A hookup or date that ended because of something completely out of your control",
      "The most unhinged thing you've done to make someone jealous",
      "A time you accidentally sent something to the wrong person and it was bad",
      "The worst thing that's ever happened to you mid-makeout",
      "A time you had to sneak out of somewhere and it did not go smoothly",
      "The most feral thing you've done when you thought no one was watching",
      "A secret about an ex you've never told anyone",
      "The worst thing you've done to get someone to stop texting you",
      "A time your friends had to physically remove you from a situation",
      "The most unhinged thing that's happened to you at 4am with someone else present",
      "A time you were caught talking about someone and had to fully commit to the lie",
      "The worst thing that's ever happened to you because of a dating app match",
      "A time you ghosted someone and later deeply regretted it",
      "The most feral thing you've done to avoid an ex at an event",
      "A secret you found out about a friend's relationship",
      "The worst thing that's ever happened to you in a shared bathroom situation",
      "A time you had to fake an emergency to leave a date",
      "The most unhinged thing an ex's friend has ever done to you",
      "A time you were caught somewhere you had no business being",
      "The worst thing that's ever happened to you because you overshared",
      "A secret you've kept about a hookup that would shock your friends",
      "The most feral thing you've done to get someone's number",
      "A time your phone betrayed you in front of someone you were dating",
      "The worst thing that's ever happened to you because of a group chat leak",
      "A time you had to pretend a hookup never happened",
      "The most unhinged thing you've done during a fight with a partner",
      "A secret code word you have with a friend for \"get me out of here\"",
      "The worst thing that's ever happened to you because of bad timing, romantically",
      "A time an ex showed up somewhere you did not expect them",
      "The most feral thing that's ever happened to you at an after-party",
      "A time you had to explain a hickey, mark, or injury with a straight face",
      "The worst thing that's ever happened to you because of a mutual friend",
      "A secret you've kept about who you actually like",
      "The most unhinged thing you've done in the name of \"getting over\" someone",
      "A time you accidentally revealed something you weren't supposed to know",
      "The worst thing that's ever happened to you because of an unlocked phone",
      "A time you had to sit through an incredibly awkward run-in with an ex",
      "The most feral thing you've done at a house party that got out of hand",
      "A secret about your dating history your parents will never know",
      "The worst thing that's ever happened to you because of a mixed signal",
      "A time you had to pick a side in a friend's breakup",
      "The most unhinged thing you've done to avoid saying \"I love you\" first",
      "A secret you've kept from a partner that you probably shouldn't have",
      "The worst thing that's ever happened to you because of a surprise visit",
      "A time you were caught snooping and had to talk your way out",
      "The most feral thing that's ever happened to you because of jealousy",
      "A secret rule you and a friend have about dating each other's exes",
      "The worst thing that's ever happened to you because you trusted the wrong person",
      "A time you had to explain your location to someone you were dating",
      "The most unhinged thing you've done to make an ex regret leaving",
      "A secret you've kept about a situationship that lasted way too long",
      "The worst thing that's ever happened to you because of a plus-one situation",
      "A time a date turned out to be someone you already knew, badly",
      "The most feral thing that's ever happened to you because of a dating app lie",
      "A secret about a friend's ex you've never revealed",
      "The worst thing that's ever happened to you because of a text sent too soon",
      "A time you had to physically hide from someone in public",
      "The most unhinged thing you've done to avoid running into a situationship",
      "A secret you've kept about how a relationship actually ended",
      "The worst thing that's ever happened to you because of an overheard conversation about you",
      "A time you had to fake enthusiasm about meeting someone's friends",
      "The most feral thing that's ever happened to you at a reunion, class or family",
      "A secret you've kept about a crush on someone completely off-limits",
      "The worst thing that's ever happened to you because of a borrowed outfit",
      "A time you had to choose loyalty over honesty and it backfired",
      "The most unhinged thing you've done because of a horoscope or tarot reading",
      "A secret you've kept about liking someone your friend also liked",
      "The worst thing that's ever happened to you because a friend group had to split after a breakup",
      "A time you had to sit next to an ex at an event with no escape",
      "The most feral thing that's ever happened to you because of alcohol and total honesty combined",
      "A secret you've kept that changed how you see a whole relationship in hindsight",
      "The worst thing that's ever happened to you because someone read your texts",
      "A time you had to lie about being single or taken for convenience",
      "The most unhinged thing you've done purely to prove a point to an ex",
      "A secret you've kept about something that happened on a \"just friends\" trip",
      "The worst thing that's ever happened to you because of bad Wi-Fi during an intimate moment",
      "A time you had to explain a very suspicious receipt or charge",
      "The most feral thing that's ever happened to you because you said yes to a dare",
      "A secret you've kept about a situationship neither of you ever defined",
      "The worst thing that's ever happened to you because of a pregnancy scare, real or false alarm",
      "A time you had to choose between honesty and keeping the peace, and picked wrong",
      "The most unhinged thing you've done at 2am that you blame entirely on the moon",
    ],
  },
  5: {
    name: "Unhinged",
    list: [
      "Stories about people who tried to have sex with something they really shouldn't have",
      "The weirdest crime you'd commit if 100% guaranteed to get away with it",
      "The most unhinged conspiracy theory you actually kind of believe",
      "The strangest body horror fact you know and can't unknow",
      "If you had to eat one non-food item for $1,000,000, what would it be",
      "The most cursed thing you've seen online that you can't unsee",
      "A hypothetical crime scene you'd stage purely for the chaos of it",
      "The weirdest thing you'd do for a million dollars, no questions asked",
      "The strangest thing you've heard about someone's situationship",
      "What you'd do with 24 hours of total, consequence-free immunity",
      "The most cursed food combination someone swears is good",
      "The weirdest thing that's ever happened to someone you know at a funeral",
      "The most unhinged thing you'd say to get out of a wedding toast",
      "A completely deranged business idea you're convinced would actually work",
      "The strangest thing you'd be willing to do live on stream for $10",
      "If you had to survive a horror movie, what unforgivable thing would you do to make it to the credits",
      "Which body part you'd eat first if it came down to it, purely hypothetically, for science",
      "The most unhinged secret society you'd start and what the initiation would be",
      "If you had to fake your own death, the plan, the excuse, and the exit strategy",
      "The most feral thing you'd do if you turned invisible for exactly 24 hours",
      "Which friend is most likely to end up as the subject of a true crime podcast, and why it tracks",
      "The worst possible way to find out you'd hooked up with someone you're related to",
      "If aliens landed tomorrow and granted one wish with a horrifying catch, what's the wish",
      "The most cursed thing you'd 3D print if there were absolutely zero rules",
      "A victimless crime you'd commit forever if you could never be caught",
      "The weirdest thing you'd smuggle across a border for $50, no further questions",
      "If you had to be cursed with the single most inconvenient superpower, what is it",
      "The most unhinged eulogy you'd secretly want someone to give at your funeral",
      "What you'd actually do trapped alone in a mall overnight with zero supervision",
      "The most deranged thing you'd do to win a reality show, morals fully optional",
      "If reincarnation wasn't real and there were truly zero consequences, what would you finally do",
      "The most cursed urban legend you half-believe is real",
      "Which one bug you'd eat for the rest of your life if forced to choose exactly one",
      "The worst way you'd want to go viral, if you had to pick",
      "Who in your friend group you'd eat first on a stranded lifeboat, hypothetically, no judgment",
      "The most unhinged item you'd steal from a museum if you knew you'd never get caught",
      "If you woke up as a cult leader tomorrow, what your cult's one rule would be",
      "The strangest thing you'd fake being an expert in to win a bar bet",
      "If you had to give up one basic bodily function forever, which and why",
      "The most cursed thing you'd say to a ghost if you knew for certain it could hear you",
      "What your villain origin story would actually be, realistically",
      "The weirdest hill you'd die on in a custody battle over a pet that isn't yours",
      "If you had to pick one animal to fight to the death, unarmed, which do you take your chances with",
      "The most unhinged thing you'd do to get revenge on a stranger who wronged you once",
      "If your body had to be found somewhere, hypothetically, what's the most embarrassing place",
      "The strangest thing you'd confess to a priest, therapist, or bartender at 2am",
      "If you had to pick your own funeral playlist, what's the one song that ruins the whole vibe",
      "The most cursed conspiracy you'd actually start if you had the resources",
      "What you'd do if you found out your soulmate was a genuinely terrible person",
      "The weirdest thing you'd do to get out of jury duty, ethics aside",
      "If you had to be the final girl or guy in a slasher movie, what's your one fatal flaw",
      "The most unhinged thing you'd do if you found out you had one year left, no consequences",
      "What cursed object you'd absolutely buy at a garage sale despite every warning sign",
      "The strangest thing you'd do if you woke up in someone else's body for a day",
      "If you had to pick a hill to die on in an alien abduction negotiation, what is it",
      "The most deranged thing you'd do to get the last item on a store shelf",
      "What you'd actually do if you found a body and no one would ever know you were there",
      "The weirdest thing you'd do to win an argument with a conspiracy theorist relative",
      "If you had to join a doomsday cult for a weekend for research purposes, which one and why",
      "The most unhinged thing you'd say in a hostage negotiation if you were the hostage",
      "What you'd actually do with a working time machine and a two-hour limit",
      "The strangest thing you'd do to avoid being the one who gets picked off first in a horror movie",
      "If you had to fight one historical figure, dead or alive, who and why",
      "The most cursed thing you'd do to get out of a group chat you're stuck in forever",
      "What you'd do if you found out your reflection had been lying to you the whole time",
      "The weirdest thing you'd barter with strangers during a full societal collapse",
      "If you had to pick the most unhinged way to be resurrected, what would it be",
      "The most deranged thing you'd do for a parking spot during a full moon, hypothetically",
      "What cursed roommate habit would actually make you move out overnight",
      "The strangest thing you'd do to convince a jury you're an alien, if that somehow got you out of a ticket",
      "If your organs went up for auction after death, which one gets the highest bid and why",
      "The most unhinged thing you'd do to win a staring contest with a crow",
      "What you'd actually do if you woke up mid-surgery and could hear everything",
      "The weirdest thing you'd do to avoid becoming a ghost story yourself",
      "If you had to pick one conspiracy to make true just by believing it hard enough, which one",
      "The most cursed thing you'd do to get out of small talk at a funeral",
      "What you'd do if your pet turned out to be plotting against you, and you had proof",
      "The strangest thing you'd do to survive being the chosen sacrifice in a horror-movie cult",
      "What you'd actually do if you found out ghosts were real but only interested in gossip",
      "The most unhinged thing you'd do to get revenge on a self-checkout machine",
      "If you had to pick a de facto arch-nemesis from your own family, who is it and why",
      "The weirdest thing you'd do to get out of paying for a group dinner",
      "What cursed talent you have that would make you a menace in a horror movie",
      "The most deranged thing you'd do to win a game of chicken with a goose",
      "If you had to choose the method, how would you want to be embarrassingly immortalized in a museum",
      "The strangest thing you'd do to prove you're not a robot to a suspicious barista",
      "What you'd actually do if you found out you were the villain in someone else's story the whole time",
      "The most unhinged thing you'd do to get out of a haunted house you paid to be in",
      "If your worst 3am thought became public record, which one ends your career",
      "The weirdest thing you'd do to win an inheritance dispute",
      "What cursed family heirloom you'd secretly love to inherit, no questions asked",
      "The most deranged thing you'd do if you found out your group chat had a mole",
      "If you had to pick a method to fake a haunting in your own house for insurance purposes, what's the plan",
      "The strangest thing you'd do to avoid jury duty by seeming unhinged on purpose",
      "What you'd actually do if a fortune teller gave you a specific, terrifyingly accurate death date",
      "The most unhinged thing you'd do to win custody of a group chat name after a friendship split",
      "If you had to pick the most cursed way to find out you're a twin separated at birth, what is it",
      "The weirdest thing you'd do to get out of a destination wedding you can't afford",
      "What cursed superstition you secretly follow even though you know it's ridiculous",
      "The most deranged thing you'd do if you found out your therapist was gossiping about you to their other clients",
      "If you had to choose your own cause of death for dramatic effect, what would it be",
      "The strangest thing you'd do to win a legal argument against a vending machine",
      "What you'd actually do if you found out your childhood imaginary friend was real the whole time",
      "The most unhinged thing you'd do to get out of being someone's emergency contact",
      "If you had to pick the most cursed place to accidentally fall asleep, where would it be",
      "The weirdest thing you'd do to avoid being recognized after doing something deeply embarrassing in public",
      "What cursed talent your family has that skipped you and you're still bitter about it",
      "The most deranged thing you'd do to win an argument with a toddler",
      "If you had to choose the most unhinged epitaph for your own tombstone, what would it say",
      "The strangest thing you'd do to convince a cult you're already one of them just to leave peacefully",
    ],
  },
};
