// THEMES — organized by unhinged level, 1 (wholesome) through 5 (unhinged).
// Deliberately a mixed bag within each level: food, movies, music, hypotheticals,
// confessions, whatever. Add more any time — arrays can be any length.

const THEMES = {
  1: {
    name: "Wholesome",
    list: [
      "Comfort foods that instantly fix a bad day",
      "Movies you could rewatch forever and never get sick of",
      "Songs that make you cry the good kind of tears",
      "A childhood show you were way too obsessed with",
      "The dream vacation you'd drop everything for",
      "The best gift you've ever given or received",
      "A meal you'd pick as your actual last meal",
      "A book that quietly changed how you see the world",
      "Smells that instantly bring back a specific memory",
      "The most \"us\" inside joke you two have",
      "A skill you wish you'd learned as a kid",
      "Your ideal lazy Sunday, minute by minute",
      "An album that got you through a specific era of your life",
      "The best meal either of you has ever cooked",
      "A stranger's small act of kindness you still think about",
    ],
  },
  2: {
    name: "Spicy",
    list: [
      "Worst first dates either of you has ever been on",
      "Unpopular food opinions you will die defending",
      "The most embarrassing thing in your search history",
      "A celebrity you'd trade lives with for exactly one week",
      "The worst fashion phase you thought was fire at the time",
      "Conspiracy theories you low-key believe",
      "The weirdest thing you've done to try to fall asleep",
      "A lie you told as a kid that spiraled way out of control",
      "The worst gift you ever had to pretend to love",
      "The most feral thing you've eaten at 2am",
      "A text you sent and immediately regretted",
      "Weird family traditions that seem normal until you say them out loud",
      "A movie everyone loves that you secretly think is bad",
      "The most chaotic thing that's happened at a family holiday",
      "A song you're embarrassed to admit you know every word to",
    ],
  },
  3: {
    name: "Chaotic",
    list: [
      "Worst decision either of you made while drunk",
      "The weirdest DM or text you've ever gotten from a stranger",
      "Something you did for a crush that mortifies you now",
      "The worst roommate horror story you have",
      "A dream so weird you had to tell someone immediately",
      "The most unhinged thing you Googled and instantly regretted",
      "A time you got away with something you definitely shouldn't have",
      "The white lie that snowballed into total chaos",
      "Something you did in public that still haunts you",
      "The most feral your group chat has ever gotten",
      "A \"we don't talk about that night\" story",
      "The weirdest internet rabbit hole you've ever fallen into",
      "The worst movie you've ever paid full price to see",
      "A time you had to fake being fine in front of everyone",
      "The most chaotic thing you've done to avoid an awkward conversation",
    ],
  },
  4: {
    name: "Feral",
    list: [
      "Worst hookup story either of you is willing to share",
      "Something embarrassing you got fully caught doing",
      "The worst breakup revenge either of you has pulled or witnessed",
      "The strangest thing you've done at 3am and questioned everything after",
      "The weirdest thing you've heard someone say during a hookup",
      "The most illegal thing you've done and fully gotten away with",
      "A time your body betrayed you at the worst possible moment",
      "The most unhinged thing an ex has ever done",
      "Weirdest thing that's ever happened on public transit near you",
      "A secret you've kept from your family that would break the internet",
      "The most chaotic thing you've done for petty revenge",
      "A time you had to lie your way out of getting caught",
      "The worst thing someone has confidently recommended you eat",
      "A situationship so strange you still can't explain it",
      "The most unhinged voicemail or text you've ever received",
    ],
  },
  5: {
    name: "Unhinged",
    list: [
      "Stories about people who tried to have sex with something they really shouldn't have",
      "The weirdest crime you'd commit if 100% guaranteed to get away with it",
      "The most unhinged conspiracy theory you actually kind of believe",
      "The strangest body horror fact you know and can't unknow",
      "If you had to eat one non-food item for $1,000,000, what would it be",
      "The most cursed thing you've seen online that you can't unsee",
      "A hypothetical crime scene you'd stage purely for the chaos of it",
      "The weirdest thing you'd do for a million dollars, no questions asked",
      "The strangest thing you've heard about someone's situationship",
      "What you'd do with 24 hours of total, consequence-free immunity",
      "The most cursed food combination someone swears is good",
      "The weirdest thing that's ever happened to someone you know at a funeral",
      "The most unhinged thing you'd say to get out of a wedding toast",
      "A completely deranged business idea you're convinced would actually work",
      "The strangest thing you'd be willing to do live on stream for $10",
    ],
  },
};
